### ISSUE TITLE
Deberías agregar una validación para verificar que el id del usuario que estás editando sea el logueado en la sesión. Sinó enviando un post con el id de otro usuario a ese archivo, podrías editarle datos de acceso o perfil a otro usuario.

### ISSUE THREAD

**Issue by julianbutti** [f4du4/EntornosGraficos2023#3]
https://github.com/f4du4/EntornosGraficos2023/blob/888bd5c84d592114e05c09534876e8d537e4d264/sdgv/controladora/usuarios/procesar_editar_mi_perfil.php#L10

**Comment by f4du4** [comment]
Perfecto profe, agregue una nueva pantalla para mostrar el error y no dejar que edite.
![image](https://github.com/f4du4/EntornosGraficos2023/assets/77935953/8da5d0f9-7009-443d-b49a-4175c8166e5f)
